name = "matterapt-website"
main = ".open-next/worker.js"
compatibility_date = "2026-01-19"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"
not_found_handling = "single-page-application"
